# Generated by Django 5.2.6 on 2026-08-02 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_logistique_bibliotheque_sync_tracking'),
        ('eleves', '0018_visitemedicale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienetablissement',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens_logistiques', to='eleves.ecole', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='marque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='prix_achat_unitaire',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name="Prix d'achat unitaire (GNF)"),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_achetee',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité achetée'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_gate',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité gâtée/perdue'),
        ),
        migrations.AddField(
            model_name='bienetablissement',
            name='quantite_utilisee',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité utilisée'),
        ),
        migrations.AlterField(
            model_name='bienetablissement',
            name='type_bien',
            field=models.CharField(choices=[('SALLE_CLASSE', 'Salle de classe'), ('BUREAU', 'Bureau'), ('LABORATOIRE', 'Laboratoire'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('TOILETTE', 'Toilette'), ('CANTINE', 'Cantine'), ('TERRAIN_SPORT', 'Terrain de sport'), ('COUR', 'Cour'), ('PARKING', 'Parking'), ('TABLE', 'Table(s)'), ('CHAISE', 'Chaise(s)'), ('ARMOIRE', 'Armoire'), ('ETAGERE', 'Étagère'), ('CLIMATISEUR', 'Climatiseur'), ('ORDINATEUR', 'Ordinateur'), ('IMPRIMANTE', 'Imprimante'), ('PROJECTEUR', 'Projecteur'), ('TABLEAU', 'Tableau'), ('GLOBE_TERRESTRE', 'Globe terrestre'), ('CARTE', 'Carte géographique'), ('COMPAS', 'Compas'), ('MARQUEUR', 'Marqueur(s)'), ('EQUERRE', 'Équerre'), ('AMPOULE', 'Ampoule(s)'), ('VENTILATEUR', 'Ventilateur'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de bien'),
        ),
        migrations.CreateModel(
            name='SuiviPapierRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('mode', models.CharField(choices=[('PAPIER', 'Papier RAM remis'), ('ARGENT', 'Argent payé à la place')], max_length=10, verbose_name='Type de contribution')),
                ('nombre_paquets', models.PositiveIntegerField(default=0, verbose_name='Nombre de paquets')),
                ('montant_paye', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant payé (GNF)')),
                ('date_remise', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_papier_ram', to='eleves.ecole', verbose_name='Établissement')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_papier_ram', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Contribution papier RAM',
                'verbose_name_plural': 'Contributions papier RAM',
                'ordering': ['-date_remise', '-date_creation'],
                'indexes': [models.Index(fields=['ecole', 'date_remise'], name='depenses_su_ecole_i_ec3748_idx'), models.Index(fields=['eleve', 'mode'], name='depenses_su_eleve_i_2bd7cf_idx')],
            },
        ),
    ]
