# Generated by Django 5.2.6 on 2026-08-03 02:28

import django.db.models.deletion
import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0008_bienetablissement_ecole_bienetablissement_marque_and_more'),
        ('eleves', '0018_visitemedicale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unite', models.CharField(choices=[('PIECE', 'Pièce'), ('PAQUET', 'Paquet'), ('BOITE', 'Boîte'), ('CARTON', 'Carton'), ('UNITE', 'Unité')], default='PIECE', max_length=10, verbose_name='Unité')),
                ('quantite_stock', models.PositiveIntegerField(default=0, help_text='Quantité totale approvisionnée. Le reste est calculé après les ventes.', verbose_name='Quantité mise en stock')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat unitaire (GNF)")),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente unitaire (GNF)')),
                ('seuil_alerte', models.PositiveIntegerField(default=5, verbose_name='Seuil d’alerte')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_fournitures_crees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_fournitures', to='eleves.ecole', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Produit de fourniture scolaire',
                'verbose_name_plural': 'Produits de fournitures scolaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='VenteFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité vendue')),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat unitaire (GNF)")),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente unitaire (GNF)')),
                ('montant_achat', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name="Coût d'achat (GNF)")),
                ('montant_vente', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='Montant vendu (GNF)')),
                ('solde', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='Solde / marge brute (GNF)')),
                ('acheteur', models.CharField(blank=True, max_length=150, verbose_name='Acheteur / bénéficiaire')),
                ('date_vente', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de vente')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('statut', models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', max_length=10, verbose_name='Statut')),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_fournitures_annulees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_fournitures_creees', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='depenses.produitfourniture', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vente de fourniture scolaire',
                'verbose_name_plural': 'Ventes de fournitures scolaires',
                'ordering': ['-date_vente', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='produitfourniture',
            index=models.Index(fields=['ecole', 'actif'], name='depenses_pr_ecole_i_fb6e24_idx'),
        ),
        migrations.AddIndex(
            model_name='produitfourniture',
            index=models.Index(fields=['ecole', 'nom'], name='depenses_pr_ecole_i_d26dda_idx'),
        ),
        migrations.AddConstraint(
            model_name='produitfourniture',
            constraint=models.UniqueConstraint(fields=('ecole', 'nom'), name='uniq_produit_fourniture_par_ecole'),
        ),
        migrations.AddIndex(
            model_name='ventefourniture',
            index=models.Index(fields=['produit', 'statut'], name='depenses_ve_produit_24c36d_idx'),
        ),
        migrations.AddIndex(
            model_name='ventefourniture',
            index=models.Index(fields=['date_vente', 'statut'], name='depenses_ve_date_ve_cca899_idx'),
        ),
    ]
