# Generated by Django 5.2.6 on 2026-08-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0009_produitfourniture_ventefourniture_and_more'),
        ('eleves', '0018_visitemedicale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_mise_disponible',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise à disposition'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='emprunt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_source', to='depenses.emprunt', verbose_name='Emprunt créé'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='exemplaire_bloque',
            field=models.BooleanField(default=False, help_text="Indique qu'un exemplaire disponible est réservé physiquement pour l'élève.", verbose_name='Exemplaire mis de côté'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='traitee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_bibliotheque_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['statut', 'date_expiration'], name='depenses_re_statut_c899ba_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['livre', 'statut', 'date_reservation'], name='depenses_re_livre_i_82eb85_idx'),
        ),
    ]
