# Generated by Django 5.2.6 on 2026-08-05 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0010_reservation_date_mise_disponible_and_more'),
        ('eleves', '0018_visitemedicale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Dépense de cuisine',
                'verbose_name_plural': 'Dépenses de cuisine',
                'ordering': ['-date', '-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Dépense de document',
                'verbose_name_plural': 'Dépenses de documents',
                'ordering': ['-date', '-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant (GNF)')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lieu_versement', models.CharField(max_length=200, verbose_name='Lieu de versement')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eleves.ecole', verbose_name='École')),
            ],
            options={
                'verbose_name': 'Versement',
                'verbose_name_plural': 'Versements',
                'ordering': ['-date', '-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbonnementInformatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sync_created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_updated_at', models.DateTimeField(auto_now=True)),
                ('sync_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.PositiveIntegerField(default=1)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name="Date d'enregistrement")),
                ('montant', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name="Montant de l'abonnement (GNF)")),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate, verbose_name="Début de l'abonnement")),
                ('date_fin', models.DateField(db_index=True, verbose_name="Fin de l'abonnement")),
                ('alerte_avant_jours', models.PositiveIntegerField(default=7, verbose_name='Alerte avant (jours)')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_informatique', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Abonnement informatique',
                'verbose_name_plural': 'Abonnements informatique',
                'ordering': ['-date_fin', 'eleve__nom'],
                'indexes': [models.Index(fields=['eleve', 'date_fin'], name='depenses_ab_eleve_i_0b66f5_idx')],
            },
        ),
    ]
