# Generated by Django 5.2.6 on 2026-07-20 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0018_visitemedicale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(blank=True, max_length=100, verbose_name='Matière')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du devoir')),
                ('description', models.TextField(blank=True, verbose_name='Consignes / description')),
                ('date_donne', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de remise du sujet')),
                ('date_remise', models.DateField(verbose_name='À rendre le')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devoirs/', verbose_name='Énoncé (fichier joint)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='eleves.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_remise', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('EXCUSE', 'Absence excusée')], default='PRESENT', max_length=10, verbose_name='Statut')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif (absence / retard)')),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve', verbose_name='Élève')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'eleve__nom', 'eleve__prenom'],
            },
        ),
        migrations.CreateModel(
            name='RemiseDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('NON_REMIS', 'Non remis'), ('REMIS', 'Remis'), ('EN_RETARD', 'Remis en retard'), ('DISPENSE', 'Dispensé')], default='NON_REMIS', max_length=10, verbose_name='Statut')),
                ('remarque', models.CharField(blank=True, max_length=200, verbose_name='Remarque')),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='vie_scolaire.devoir', verbose_name='Devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises_devoirs', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Remise de devoir',
                'verbose_name_plural': 'Remises de devoirs',
                'ordering': ['eleve__nom', 'eleve__prenom'],
            },
        ),
        migrations.AddIndex(
            model_name='devoir',
            index=models.Index(fields=['classe', 'date_remise'], name='vie_scolair_classe__5a4cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['classe', 'date'], name='vie_scolair_classe__3d8b40_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['statut'], name='vie_scolair_statut_64ab3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='remisedevoir',
            unique_together={('devoir', 'eleve')},
        ),
    ]
