# Generated by Django 5.2.6 on 2026-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0015_historiqueeleve_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='allergies',
            field=models.TextField(blank=True, help_text='Allergies connues (alimentaires, médicamenteuses, etc.)', null=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='maladies_chroniques',
            field=models.TextField(blank=True, null=True, verbose_name='Maladies chroniques / antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='observations_medicales',
            field=models.TextField(blank=True, help_text='Toute autre information utile pour le personnel encadrant (régime alimentaire, peur particulière, etc.)', null=True, verbose_name='Observations médicales'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='traitement_en_cours',
            field=models.TextField(blank=True, help_text='Médicaments pris régulièrement, posologie', null=True, verbose_name='Traitement en cours'),
        ),
    ]
