# Generated by Django 5.2.6 on 2026-07-11 22:23

import eleves.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0016_eleve_allergies_eleve_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo du batiment de l'ecole (affichee sur le livret scolaire)", null=True, upload_to='ecoles/images/', validators=[eleves.validators.validate_photo_size], verbose_name="Photo de l'ecole"),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ecoles/logos/', validators=[eleves.validators.validate_logo_size]),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/photos/', validators=[eleves.validators.validate_photo_size], verbose_name='Photo'),
        ),
    ]
