# Generated by Django 5.2.6 on 2026-07-12 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0017_alter_ecole_image_alter_ecole_logo_alter_eleve_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(verbose_name='Date et heure de la visite')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif de la visite')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température (°C)')),
                ('symptomes', models.TextField(blank=True, null=True, verbose_name='Symptômes observés')),
                ('soins', models.TextField(blank=True, null=True, verbose_name='Soins / médicaments administrés')),
                ('statut', models.CharField(choices=[('RETOUR_CLASSE', 'Retourné en classe'), ('EN_OBSERVATION', 'En observation'), ('RENVOYE_MAISON', 'Renvoyé à la maison'), ('HOPITAL', 'Orienté vers un centre de santé')], default='RETOUR_CLASSE', max_length=20, verbose_name='Suite donnée')),
                ('parent_contacte', models.BooleanField(default=False, verbose_name='Parent contacté')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_medicales', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Visite médicale',
                'verbose_name_plural': 'Visites médicales',
                'ordering': ['-date_visite'],
                'indexes': [models.Index(fields=['eleve', '-date_visite'], name='eleves_visi_eleve_i_37d019_idx')],
            },
        ),
    ]
