# Generated by Django 5.2.6 on 2026-09-02 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0020_eleve_test_accueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='afficher_filigrane',
            field=models.BooleanField(default=True, verbose_name='Afficher le logo en filigrane sur les documents'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_accent',
            field=models.CharField(default='#FFC83D', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name="Couleur d'accent"),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_avertissement',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Avertissement / attention'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_bus',
            field=models.CharField(default='#0EA5E9', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Bus'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_cantine',
            field=models.CharField(default='#EC4899', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Cantine'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_depenses',
            field=models.CharField(default='#DC3545', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Dépenses'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_eleves',
            field=models.CharField(default='#3563AE', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Élèves'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_notes',
            field=models.CharField(default='#7C3AED', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Notes'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_paiements',
            field=models.CharField(default='#198754', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Paiements'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_carte_salaires',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cartes Salaires'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_danger',
            field=models.CharField(default='#DC3545', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Danger / défavorable'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_fond_clair',
            field=models.CharField(default='#EEF4FF', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Fond clair des documents'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_principale',
            field=models.CharField(default='#3563AE', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_secondaire',
            field=models.CharField(default='#244A8A', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur secondaire'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_succes',
            field=models.CharField(default='#198754', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Succès / favorable'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_texte',
            field=models.CharField(default='#1F2937', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur hexadécimale valide, par exemple #3563AE.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Couleur du texte'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='opacite_filigrane',
            field=models.FloatField(default=0.08, help_text='Valeur comprise entre 0 et 0,25. Recommandé : 0,08.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.25)], verbose_name='Opacité du filigrane'),
        ),
    ]
