# Generated by Django 5.2.6 on 2026-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0021_ecole_charte_graphique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('ATTENTE_PAIEMENT', 'En attente du premier paiement'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé')], db_index=True, default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut_avant_suppression',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('ATTENTE_PAIEMENT', 'En attente du premier paiement'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé')], max_length=20, verbose_name='Statut avant suppression'),
        ),
    ]
