# Generated by Django 5.2.17 on 2026-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0022_attente_premier_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_1_lien',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Personne autorisée 1 - Lien avec l'enfant"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_1_nom',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Personne autorisée 1 - Nom complet'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_1_piece',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Personne autorisée 1 - N° pièce d'identité"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_1_telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Personne autorisée 1 - Téléphone'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_2_lien',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Personne autorisée 2 - Lien avec l'enfant"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_2_nom',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Personne autorisée 2 - Nom complet'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_2_piece',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Personne autorisée 2 - N° pièce d'identité"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='personne_autorisee_2_telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Personne autorisée 2 - Téléphone'),
        ),
    ]
