# Generated by Django 5.2.6 on 2026-08-09 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_systemlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetSupprime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=120, verbose_name='Modèle')),
                ('object_pk', models.CharField(db_index=True, max_length=64, verbose_name='Identifiant')),
                ('object_repr', models.CharField(max_length=250, verbose_name='Objet')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données sérialisées')),
                ('supprime_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Supprimé le')),
                ('restaure', models.BooleanField(db_index=True, default=False, verbose_name='Restauré')),
                ('restaure_le', models.DateTimeField(blank=True, null=True, verbose_name='Restauré le')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objets_supprimes', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Objet dans la corbeille',
                'verbose_name_plural': 'Corbeille des suppressions',
                'ordering': ['-supprime_le', '-id'],
            },
        ),
    ]
