# Generated by Django 5.2.6 on 2026-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0009_complete_sync_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremise',
            name='motif_application',
            field=models.CharField(blank=True, choices=[('CLIENT_FIDELE', 'Client fidèle'), ('PROMOTION', 'Promotion'), ('ERREUR_COMMERCIALE', 'Erreur commerciale'), ('PARTENAIRE', 'Partenaire'), ('GESTE_COMMERCIAL', 'Geste commercial'), ('NE_PAIE_RIEN', 'Ne paie rien'), ('LA_MOITIE', 'La moitié')], default='', max_length=30, verbose_name='Motif de la remise'),
        ),
        migrations.AddField(
            model_name='paiementremise',
            name='portee_tranches',
            field=models.CharField(blank=True, default='', help_text='Numéros de tranches couvertes, séparés par des virgules (ex: 1,2)', max_length=10, verbose_name='Tranches concernées'),
        ),
    ]
