# Generated by Django 5.2.6 on 2026-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0011_historiquemodificationpaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementremise',
            name='deduite_du_paiement',
            field=models.BooleanField(default=False, help_text="Le montant du reçu a été ramené au net de cette remise. Permet de reconstituer le montant brut lors d'une réédition ou d'une annulation.", verbose_name='Déduite du montant du reçu'),
        ),
    ]
