# Generated by Django 5.2.6 on 2026-07-12 07:36

import django.db.models.deletion
import eleves.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0018_visitemedicale'),
        ('notes', '0008_complete_sync_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteCulturelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(help_text="Photo de l'activité (max 3 Mo)", upload_to='activites_culturelles/', validators=[eleves.validators.validate_photo_size], verbose_name='Image')),
                ('date_activite', models.DateField(blank=True, null=True, verbose_name="Date de l'activité")),
                ('publie', models.BooleanField(default=True, help_text="Décocher pour masquer l'activité de la page publique", verbose_name='Publié sur le site')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activites_culturelles', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Activité culturelle',
                'verbose_name_plural': 'Activités culturelles',
                'ordering': ['-date_activite', '-date_creation'],
            },
        ),
    ]
