# Generated by Django 5.2.6 on 2026-08-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0019_elevecorbeille_eleve_est_dans_corbeille_and_more'),
        ('synchronisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_change_id', models.BigIntegerField(default=0)),
                ('derniere_synchro', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursor', to='eleves.ecole')),
            ],
            options={
                'verbose_name': 'Repere de synchronisation',
                'verbose_name_plural': 'Reperes de synchronisation',
            },
        ),
    ]
