# Generated by Django 5.2.6 on 2026-08-16

from django.db import migrations, models


def renseigner_source_heures(apps, schema_editor):
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    EtatSalaire.objects.filter(
        enseignant__type_enseignant='SECONDAIRE',
    ).update(source_heures='POINTAGE')
    EtatSalaire.objects.exclude(
        enseignant__type_enseignant='SECONDAIRE',
    ).update(source_heures='FIXE')


def reinitialiser_source_heures(apps, schema_editor):
    EtatSalaire = apps.get_model('salaires', 'EtatSalaire')
    EtatSalaire.objects.update(source_heures='POINTAGE')


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0005_etatsalaire_taux_horaire_applique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='type_enseignant',
            field=models.CharField(
                choices=[
                    ('GARDERIE', 'Garderie'),
                    ('MATERNELLE', 'Maternelle'),
                    ('PRIMAIRE', 'Primaire'),
                    ('SECONDAIRE', 'Secondaire (taux horaire)'),
                    ('CADRE', 'Cadre / personnel administratif'),
                    ('ADMINISTRATEUR', 'Administrateur'),
                ],
                max_length=20,
                verbose_name="Type d'enseignant",
            ),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='source_heures',
            field=models.CharField(
                choices=[
                    ('POINTAGE', 'Pointages arrivée / départ'),
                    ('MENSUEL', 'Saisie globale des heures mensuelles'),
                    ('FIXE', 'Salaire fixe négocié'),
                ],
                default='POINTAGE',
                help_text=(
                    "Indique si le salaire vient des pointages ou d'une "
                    "saisie mensuelle globale"
                ),
                max_length=20,
                verbose_name='Source des heures',
            ),
        ),
        migrations.RunPython(
            renseigner_source_heures,
            reinitialiser_source_heures,
        ),
    ]
