# Generated by Django 5.2.6 on 2026-09-05 20:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0008_enseignant_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='primes_mensuelles',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Montant proposé sur chaque nouvel état de salaire, ajustable pour le mois concerné.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes mensuelles (GNF)'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='type_enseignant',
            field=models.CharField(choices=[('GARDERIE', 'Garderie'), ('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire (taux horaire)'), ('CADRE', 'Cadre / personnel administratif'), ('ADMINISTRATEUR', 'Administrateur'), ('CHAUFFEUR', 'Chauffeur'), ('VIGILE', 'Vigiles'), ('ENTRETIEN', 'Service entretien'), ('NOUNOU', 'Nounou'), ('RESTAURATION', 'Restauration')], max_length=20, verbose_name="Type d'enseignant"),
        ),
    ]
