# Generated by Django 5.2.17 on 2026-09-24 21:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaires', '0009_personnel_primes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, help_text='Numéro matricule repris sur les états et bulletins de paie', max_length=30, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='jours_travailles',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide pour reprendre le nombre de jours pointés.', null=True, validators=[django.core.validators.MaxValueValidator(31)], verbose_name='Jours travaillés'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_anciennete',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'ancienneté"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_craie_revision',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de craie / révision'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_eloignement',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prime d'éloignement"),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_exceptionnelle',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime exceptionnelle'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_fonction',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de fonction'),
        ),
        migrations.AddField(
            model_name='etatsalaire',
            name='prime_performance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prime de performance'),
        ),
        migrations.AlterField(
            model_name='etatsalaire',
            name='primes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total de toutes les primes (rubriques détaillées + autres primes).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes'),
        ),
    ]
